services:
  seerr-notifier:
    image: jedrzejme/seerr-notifier:v2.3.0
    container_name: seerr-notifier
    ports:
      - "8787:8787" # <Host Port>:<Container Port (do not change)>
    volumes:
      - ./wrangler.jsonc:/app/wrangler.jsonc:ro
      - ./templates:/app/templates
    init: true
    mem_limit: 128m
    environment:
      NODE_OPTIONS: --max-old-space-size=64
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
